import { Tree } from './tree.js';
import { Node } from './node.js';
import { sortAndUniqueArray, prettyPrint, doubleNum, log } from './utils.js';
import { Queue } from './queue.js';

// const array = [1, 7, 4, 23, 8, 9, 4, 3, 5, 7, 9, 67, 6345, 324];
// const array = [1, 2, 3, 4, 5, 6, 7, 8, 9];
const array = [
  1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
];
const sortedAndUniqueArray = sortAndUniqueArray(array);
const tree = new Tree(sortedAndUniqueArray);
// const queue = new Queue();
// // const node = new Node(0);
// console.log(queue.queue);
// console.log(queue.end);
// queue.enqueue(new Node(0));
// console.log(queue.queue);
// console.log(queue.end);
// queue.enqueue(new Node(1));
// console.log(queue.queue);
// console.log(queue.end);
// queue.enqueue(new Node(2));
// console.log(queue.queue);
// console.log(queue.end);
// queue.enqueue(new Node(3));
// console.log(queue.queue);
// console.log(queue.end);
// queue.enqueue(new Node(4));
// console.log(queue.queue);
// console.log(queue.end);
// queue.enqueue(new Node(5));
// console.log(queue.queue);
// console.log(queue.end);
// queue.enqueue(new Node(6));
// console.log(queue.queue);
// console.log(queue.end);
// console.log(queue.dequeue().data);
// console.log(queue.queue);
// console.log(queue.end);
// console.log(queue.front);
// console.log(queue.queue[0].left);

// tree.levelOrderForEachRecur(doubleNum);
// tree.levelOrderForEachRecur(log);
// console.log('--------------------------');
// tree.levelOrderForEach(doubleNum);
// tree.levelOrderForEach(log);
// tree.inOrderForEach(log);
// tree.inOrderForEach(doubleNum);
// console.log('--------------------------');
// tree.preOrderForEach(log);
// tree.preOrderForEach(doubleNum);
// console.log('--------------------------');
// tree.postOrderForEach(log);
// tree.postOrderForEach(doubleNum);
tree.height(5);
tree.height(2);
tree.height(7);
tree.height(55);
tree.height(-1);
tree.height(100);
// console.log(sortedAndUniqueArray);
// console.log(tree.root.data);
// console.log(tree.includes(8));
// console.log(tree.includes(4));
// console.log(tree.includes(67));
// console.log(tree.includes(1));
// console.log(tree.includes(5));
// console.log(tree.includes(9));
// console.log(tree.includes(324));
// console.log(tree.includes(3));
// console.log(tree.includes(7));
// console.log(tree.includes(23));
// console.log(tree.includes(6345));
// console.log(tree.includes(255));
// console.log(tree.includes(122));
// console.log(tree.includes(6892));
// console.log(tree.includes(2456));
// console.log(tree.includes(1112));
// console.log(tree.includes(3452));
// console.log(tree.includes(672));
// console.log(tree.includes(92));
// console.log(tree.includes(2));
// console.log(tree.includes(22));
console.log(prettyPrint(tree.root));

// console.log(tree.insert(8));
// console.log(tree.insert(2));
// console.log(tree.insert(67));
// console.log(tree.insert(27));
// console.log(tree.insert(5));
// console.log(tree.insert(200));
// console.log(tree.insert(201));
// console.log(tree.insert(202));
// console.log(tree.insert(203));
// console.log(tree.insert(204));
// console.log(tree.insert(205));
// console.log(tree.insert(206));
// console.log(tree.insert(207));
// console.log(prettyPrint(tree.root));
// console.log(tree.deleteItem(2));
// console.log(prettyPrint(tree.root));
// console.log(tree.deleteItem(8));
// console.log(prettyPrint(tree.root));
// console.log(tree.deleteItem(206));
// console.log(prettyPrint(tree.root));
// console.log(tree.insert(22));
