import { Tree } from './tree.js';
import { sortAndUniqueArray, prettyPrint } from './utils.js';

const array = [1, 7, 4, 23, 8, 9, 4, 3, 5, 7, 9, 67, 6345, 324];
const sortedAndUniqueArray = sortAndUniqueArray(array);
const tree = new Tree(sortedAndUniqueArray);
// console.log(sortedAndUniqueArray);
console.log(prettyPrint(tree.root));
console.log(tree.root.data);
console.log(tree.includes(8));
console.log(tree.includes(4));
console.log(tree.includes(67));
console.log(tree.includes(1));
console.log(tree.includes(5));
console.log(tree.includes(9));
console.log(tree.includes(324));
console.log(tree.includes(3));
console.log(tree.includes(7));
console.log(tree.includes(23));
console.log(tree.includes(6345));
console.log(tree.includes(255));
console.log(tree.includes(122));
console.log(tree.includes(6892));
console.log(tree.includes(2456));
console.log(tree.includes(1112));
console.log(tree.includes(3452));
console.log(tree.includes(672));
console.log(tree.includes(92));
console.log(tree.includes(2));
console.log(tree.includes(22));
